[[redirects]]
from = "/grid/ofertas"
to = "/index"
status = 301

[[redirects]]
from = "/contato"
to = "/pages/contato"
status = 301

[[redirects]]
from = "/bolsa-redonda-de-palha-rattan-artestore-palha-crua"
to = "/index"
status = 301

[[redirects]]
from = "/busca"
to = "/index"
status = 301

[[redirects]]
from = "/atacado.bolsadepalha.artestore.com.br/"
to = "/index"
status = 301

[[redirects]]
from = "/cangas/"
to = "/index"
status = 301

[[redirects]]
from =  "/braceletees/"
to = "/pulseira-masculina/"
status = 301

[[redirects]]
from =  "/acessorios/"
to = "/index"
status = 301

[[redirects]]
from =  "/bolsas/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from =  "/carteira-de-palha/"
to = "/clutches-e-carteiras/"
status = 301

[[redirects]]
from =  "/carteiras-clutch-festa-casamento/"
to = "/clutches-e-carteiras/"
status = 301

[[redirects]]
from =  "/lencos/"
to = "/lencos-echarpes-cachecois-pashminas/"
status = 301

[[redirects]]
from = "/bolsas-redondas/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-de-palha-redonda-g-rattan-com-alca-de-couro-com-detalhes-vazados/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-de-palha-redonda-rattan-com-desenho-estrela-com-alca-de-couro/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-de-palha-redonda-g-rattan-com-alca-de-couro-com-detalhes-vazados-branca/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-de-palha-redonda-g-rattan-vazada-branca-com-conchinhas-buzios/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-de-palha-cestinha-redonda-pequena/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-de-palha-trico-sacola-praia-trancada-com-alca-de-madeira-crua-natural/"
to = "/bolsas-de-praia/"
status = 301

[[redirects]]
from = "/bolsa-redonda-extra-grande-de-palha-e-couro-com-franjas-e-alca-redonda/"
to = "/bolsas-de-praia/"
status = 301

